### PR TITLE
Add helm chart for installing into kubernetes

### PR DESCRIPTION
**Pull request by johnwc**
Once merged, the index.yaml and readme.md can be updated to reference this repo instead of my fork for the urls.

Steps to release new version.
 1. Deploy new version to docker hub with tag of new version. Record image digest. (tag should be same as `appVersion` used below)
 2. Update `appVersion` and `version` in chart.yaml file. 
 3. Build chart tgz file.
 4. Add new row under `powerdns-admin` in index.yaml, copying one of the other rows as template, updating `appVersion`, `digest`, `version`, and `urls`. (Url should point to new tgx file in release.)

To build the tgz file for each release, run the following command from the `deploy` directory. Then attach the powerdns-admin-<version>.tgz file to the github release.
```
> helm package .\PowerDNS-Admin
```

### CODE REVIEW

**Comment by jbe-dw** [comment]
Hello,

Thank you for submitting. I'm waiting for @RGanor feedback on Kube.

Regards

**Comment by AgentTNT** [comment]
Hi @johnwc! Thank you for submitting this PR. Can you please rebase with the latest code so we may take a look again and ensure the helm chart will work as expected? We apologize for the delay. Thank you!

**Comment by johnwc** [comment]
@AgentTNT I merged your updates a few weeks ago, and just installed it on new K8s cluster. So, I would say this has been tested with latest.

**Comment by johnwc** [comment]
@AgentTNT @AzorianMatt is the latest v0.4.1 packaged and pushed to docker? There is one that says latest, but it is 7 months old.

**Comment by johnwc** [comment]
I did what was asked, is this going to get merged?

**Comment by johnwc** [comment]
@AgentTNT @AzorianMatt Anyone around?

**Comment by AzorianMatt** [comment]
> @AgentTNT @AzorianMatt Anyone around?

Around yes, active no.

**Comment by johnwc** [comment]
@AzorianMatt can we get this approved before the stale bots close it? It has been tested and updated as requested

**Comment by AzorianMatt** [comment]
@johnwc I don't believe it will be automatically closed now that there is this communication exchange. Unfortunately, we just aren't active on the project right now so nothing will get done with this.

**Comment by johnwc** [comment]
@AzorianMatt this is a pull request, all it is waiting is for someone to accept it and it will merge the changes and close the RP.

**Comment by AzorianMatt** [comment]
@johnwc I don't know how else to tell you, it's never quite that simple on this project. At this point, without enough active resources to see these merges through with proper testing, I'm not risking any further disruptions to stability. Too many times, the simplest things have turned into quite a mess.

Perhaps if the community had been a little more favorable to the project when we were giving it our all, we might be a little more motivated to get things done today.

Being perfectly honest, life has thrown us some curveballs and that is now getting our priority. I don't mean to sound too sour about it, but we repeatedly got an overwhelming lack of effort from many of those that wanted movement on the project, without really offering up much efforts of their own. That really starts to burn people after a while. Not to mention an overwhelming show of entitlement through some of the semi-recent interactions I've had with community members.

I'm not killing the project, but it's not getting any priority in the immediate future. I've collected enough feedback to determine that many community members, are perfectly content with what they get out of it at this time. For that reason, I don't feel it's pressing to produce new changes when there is still a backlog of more pressing things.

**Comment by johnwc** [comment]
@AzorianMatt this PR was create almost a year and a half ago... This does not introduce any change to anything existing, this adds the ability to easily install the project in K8s environments.

**Comment by AzorianMatt** [comment]
@johnwc if you didn't notice, this PR includes modifications to the project read me which is a mess already. Ergo, it's not just a simple click in weight like you continue to assert.

Yes it was completed a long time ago. The project had many difficulties though, especially with extra help that was any bit reliable. I put out many calls for help, and I don't recall seeing you show up to the meetings with regular devotion.

This is exactly the problem that has driven us away. None of us made any money for any of these efforts, all the while that time could have been used for paid client work at a healthy billable rate.

It would be appreciated if you're approach didn't seem to assert that this is anyone's obligation at this point.

Per your point about this PR enabling the project to be easily installed in K8 environments, it already can with the total absence of this. I know I'm not alone when I say that a number of us, have long since had our own K8 files for this project. This is likely why there hasn't been a real demand on this particular request.

For that matter, I don't know why it's so important for you to see these files in the project repository suddenly. I have no doubt that you have deployed it in kubernetes already.

**Comment by AzorianMatt** [comment]
> @johnwc if you look back at this entire thread that has taken place today, there wasn't so much as a please or thank you. This is precisely the reason the few of us that were dedicated, are pretty well over it at this point. We've received little thanks but plenty of entitlement.

And being perfectly honest, many of the people that did come along to help briefly, we're only there to push their own agenda for their particular needs. The community now gets what it asked for.

My time is only for sale at this point, I'm no longer giving it away so freely.

**Comment by johnwc** [comment]
@AzorianMatt dude... if you are so sour with this project, then pass it on to someone else. Rather than gatekeep improvements. This is not how you run a community project. AT ALL! Especially if you are waiting for someone to pay you! I am setting the stage that it is an obligation based on the reply this PR got back in JUNE, I completed the updates as requested, but no progress afterwards on merging it. I am pushing to get the PR closed so that I can mark this complete from my end and clean up repos on my side that are just waiting for PRs to be completed.

I love how all you sour-bitten project owners state you all put out requests for help, and no one showed up to your meetings. How exactly do you expect anyone to show up when your requests for help fall on deaf ears, because your request was in a form of an update to a readme file or of the likes? Do you think we do nothing but constantly monitor the repo??? I know I am speaking for the majority when I say, I never received any notification that you were requesting help from others.

AND..... how dare you chastise people volunteering their time to add new features to an open-source project, only because they wanted to add a feature that they needed and felt it could benefit others. That is one of the main reasons OSS exists today, is because of those volunteers' adding features that benefits themselves and were generous to share!

And I am really sorry if you personally got into OSS because you thought you were going to make money off of it. That is not what OSS is about at all!!!

**Comment by johnwc** [comment]
@AzorianMatt there you go, as you wish. All content added to readme is removed and moved into its own file. Now there is nothing changed to stop this from merging.

**Comment by AzorianMatt** [comment]
@johnwc it's abundantly clear from your reply that my message was completely lost on you. How dare you accuse me of being all about the money based on what I said. This was never about the money. If it was about the money, I wouldn't have dumped so much time into the project already while sacrificing plenty of opportunity to turn that time into capital for myself.

Furthermore, how dare you tell me how the project should be ran. All the opportunity in the world was there from the beginning for you to have stepped up and taken ownership before I did when no one else showed any interest.

As for the people I referred to that showed up to push their own interest solely, I could have lived with that. What I didn't care for are false promises, repeatedly. It's hard to put together a good plan for progress, when every part of it fails at every opportunity due to the human aspect being so unreliable.

As for you being upset because a request was made for you to update the PR for a merge without that following through, yeah I get it, it sucks. But life happens to people and things come up, and priorities still must be managed. Your whining about that is absurd, as though this is somehow an unacceptable occurrence. That reaction asserts that these things aren't a part of life. If you think you have a reason to be upset, how do you think I feel? My feelings clearly don't matter to you.

As for your assertions about the seemingly minimal effort for calls to action, I didn't just put out updates on the project repo and call it square. I put out numerous updates on different social media platforms, started a project Discord server, gave it a little more professional branding, setup a private chat server, registered a project domain name, and personally reached out to my own professional peers trying to elicit help from them on this effort as well.

So maybe before you go making such stupid assumptions and running your mouth like you just did, perhaps you should have stepped back and thought a little more about what you don't know. It's not my problem that you missed all of the different opportunities that were put out there, in many places. You don't get to use that as some sort of excuse here.

Lastly, it's beyond insulting that you just blew all of that shit at me, and then somehow think that I'm going to see your request through just because you pulled out the file I don't want to deal with? You have a ridiculous view of how you think people should respond to that kind of treatment. We've made it this far in the conversation, and there still hasn't been a pleaser thank you. Instead, you essentially just accused me of being a greedy, selfish, dick.

I ought to ban your account from the project to cause you more inconvenience. You certainly need some form of consequence for this behavior. It sure as hell isn't about to be rewarded with getting what you want.

Asshole.

**Comment by johnwc** [comment]
@AzorianMatt it's abundantly clear from your reply that my message was completely lost on you. You made it very clear that this was about getting paid, and you that you did not get what you were expecting.

I am not going to waist me time reading your exaggerated excuse, just let me know if you are going to accept the PR or not.

**Comment by AzorianMatt** [comment]
@johnwc go fuck yourself prick.

**Pull request closed without merging**
