### PR TITLE
Add OIDC env vars and set SAML_ENABLED as False if unset

### LINKED ISSUE #1334: Need OpenID Connect OAuth env vars support
I would like to support some OIDC vars to enable OpenID Connect OAuth within docker env vars as SAML enabling works
Moreover, I would like to support metadata url discovery.

### PR DESCRIPTION
**Pull request by ymage**
Fix #1334

### CODE REVIEW

**Comment by ymage** [comment]
Rebased. Still works :)

**Comment by AzorianMatt** [comment]
@ymage would you mind verifying if [PR 1397](https://github.com/PowerDNS-Admin/PowerDNS-Admin/pull/1397) effectively replaced the efforts of this PR appropriately?

**Comment by ymage** [comment]
Hi @AzorianMatt 

Well, it looks like a better good start.

I would like to add 2 more things from my PR :
1. the docker_config part in the configs/docker_config.py file from my PR to get it enabled from ENV vars.
2. the default value for SAML_ENABLED as False as you can see in powerdnsadmin/routes/index.py

Wdyt ?

**Comment by ymage** [comment]
I updated my PR to keep the needed part

**Pull request merged**
