### PR TITLE
Local Password Quality Policy

### PR DESCRIPTION
**Pull request by kkmanos**
This PR addresses posted issue #989.

[Our team](https://www.gunet.gr/en) specializes on identity security, and as such, cannot stress enough the importance of external authentication services, such as OIDC or SAML. However, we understand that in some limited scenarios, Local DB authentication is the only possible solution. For this reason, we have increased the security of local authentication, by introducing Local Password Complexity Requirements.

The password requirements being enforced are a subset of the [LDAP Wiki Password Quality Policy](https://ldapwiki.com/wiki/Password%20Quality).

When choosing a password, users are provided with interactive feedback, assisting them in creating a secure password.

Attributes such as the minimum length, the minimum number of capital letters, or the minimum number of special characters required can be configured in admin settings (on Settings > Authentication > General).

### CODE REVIEW

**Comment by RGanor** [comment]
Do you only enforce password policy on client side? I think that if we gonna implement such feature we'll also need to enforce it on server side, because client side can be easily evaded.

**Comment by kkmanos** [comment]
Our feature enforces password policy on the client side, as we deemed it important to provide users with live feedback as soon as they type their password. We initially did not enforce it on the server side, because a user who bypasses the front-end check only does harm to themselves and nobody can abuse this evasion to pose a threat to the rest of the application. However, after your request, we now enforce these requirements on the server side as well.

**Comment by zoeller-freinet** [comment]
Thank you for this contribution, a password policy feature for local DB authentication, even a very basic one, has been sorely missing.

Have you considered using the output of a password strength estimation library, like zxcvbn [1] [2], and slimming down the policy checking logic a bit in return (perhaps `must_not_contain` in combination with zxcvbn's `guesses_log10` and `score` might suffice)?

The added js in `register.html` and `user_profile.html` is very similar, is there a way to deduplicate it?

---
[1] https://github.com/dropbox/zxcvbn (this is js, a Python implementation is linked in the README.md)
[2] https://lowe.github.io/tryzxcvbn/

**Comment by 4censord** [comment]
I would argue this needs a different ruleset that also takes lenght into acount:

Arguably strong passwords that get rejected:
```
R9JkMDtibXJtsJxZDF1j7aPh1pXKxL59
fIpQ4RO6p2FvvGlDVHQuDlX1Cqx3JK9sGeEABCdL9uUFjgxsKrUoHOheCBNVJVJB
```

but some, arguably weak passwords get allowed:
```
aaaaAAA11$
PASSword123!
```

**Comment by kkmanos** [comment]
Hello @zoeller-freinet ,
your suggestion was taken into account. In this merge, I added the zxcvbn python package in the backend. The two password policy implementations are conflicting, so I decided to maintain the implementation of character-specific password policy. The administrator will have the ability to switch between those two.

**Comment by AzorianMatt** [comment]
@kkmanos are you still actively involved enough to see this one through with current changes or should I close it?

**Comment by kkmanos** [comment]
Hello @AzorianMatt ,
I would suggest that you close this PR.
Unfortunately, I am no longer involved into the project, as it would be difficult for me to find time to review and update.

**Comment by AzorianMatt** [comment]
@kkmanos thank you for the follow-up!

**Comment by nkukard** [comment]
> @kkmanos are you still actively involved enough to see this one through with current changes or should I close it?

It would be a bit of a shame to loose this patch, a password security policy is a requirement for many government-related organizations.

Could I kindly ask what is still outstanding? just a re-base against 'dev'? it looks like @kkmanos addressed the feedback.

I wouldn't mind taking a look at rebasing and testing if you're still interested in it @AzorianMatt ?

**Comment by AzorianMatt** [comment]
@nkukard it's hard to say on this one but a rebase would be the minimal. Given how much time has passed with all the changes, I would imagine it will prove to be slightly more challenging to get this one merged due to likely conflicts. If you want to take a crack at it, I would certainly welcome the changes!

**Comment by nkukard** [comment]
> @nkukard it's hard to say on this one but a rebase would be the minimal. Given how much time has passed with all the changes, I would imagine it will prove to be slightly more challenging to get this one merged due to likely conflicts. If you want to take a crack at it, I would certainly welcome the changes!

I'll take a quick crack at it and revert back soon.

**Comment by nkukard** [comment]
@AzorianMatt So I spent quite a few hours on this one to try see what I could do. You were right that a substantial amount of time and work would be required to rebase it against the current dev branch. I'm down to about 700 lines of changes now. I'm not sure I have the time to finish though.

If we were to drop the live feedback which is a substantial component to the diff and just reject the password in the various routes it would simplify things a great deal, at least to get *something* working that can be improved apon. This is currently how almost all the current errors are returned.

I'm also not sure I entirely like the current approach of having conventional password character requirements *or* complexity based password requirement, ideally imho it would be nice to be able to pick a combination of both. ie. be able to set the character requirements; and/or be able to set the complexity requirement of that password.

I'm not sure how you feel about this approach, 1) drop the live feedback and reject the password in the same way other validations are done; and 2) allow the functionality of setting conventional password character requirements along with complexity requirements at the same time.

**Comment by AzorianMatt** [comment]
@nkukard I complete understand!

I didn't realize that the current PR actually took this particular approach which most certainly over-complicates the matter. While live feedback might be cool in many ways and certainly useful, I'm more than happy with the legacy app receiving the more traditional approach the follows the same flow present in most other areas of the app.

I also like your proposed approach for allowing the convention options / requirements. I definitely don't want to roll out a new feature that actually creates an impedance for more users (as it sounds like this one most certainly would).

Thanks!

**Comment by nkukard** [comment]
@AzorianMatt  How does this look?
Screenshot_20230316_151100

**Comment by nkukard** [comment]
oh, ignore the spelling mistakes :)

**Comment by AzorianMatt** [comment]
@nkukard I love it!!! If you will, please rebase your changes to the dev branch and let me know once the PR is fully ready for review, and I'll work on getting it merged!

**Comment by AzorianMatt** [comment]
This PR has been superseded by [PR 1457](https://github.com/PowerDNS-Admin/PowerDNS-Admin/pull/1457/).

**Pull request closed without merging**
