### PR TITLE
per user permissions

### PR DESCRIPTION
**Pull request by steschuser**
Expand Permission System to grant on a per user basis.

Add table user_permissions 
Add route /admin/userpermissions
Edit Template admin_edit_users.html
Add switch to enable new permission model in Settings
Expand decorators as well
When creating Users, UserPermissions are created as well
I

### CODE REVIEW

**Comment by benshalev849** [comment]
When you try and create a user it gives this error:
```
  File "/var/www/html/powerdns-admin/powerdnsadmin/decorators.py", line 32, in decorated_function
    return f(*args, **kwargs)
  File "/var/www/html/powerdns-admin/powerdnsadmin/routes/admin.py", line 124, in edit_user
    current_app.logger.info(userperms)
UnboundLocalError: local variable 'userperms' referenced before assignment
```

**Comment by steschuser** [comment]
What kind of User is that?
LDAP? Local?

Can y

**Comment by benshalev849** [comment]
> What kind of User is that?
> LDAP? Local?

Local

**Comment by steschuser** [comment]
Im not seeing that line..
https://github.com/steschuser/PowerDNS-Admin/blob/d2d7a4cc21945f7153f623b2250262d731e73fd0/powerdnsadmin/routes/admin.py#L124

There should be no current_app.logger.info(userperms) on line 124
Can you remove that statement and give me traceback?

**Comment by benshalev849** [comment]
> Im not seeing that line..
> https://github.com/steschuser/PowerDNS-Admin/blob/d2d7a4cc21945f7153f623b2250262d731e73fd0/powerdnsadmin/routes/admin.py#L124
> 
> There should be no current_app.logger.info(userperms) on line 124
> Can you remove that statement and give me traceback?

Kk
Ill test it tmrw probably and let you know

**Comment by benshalev849** [comment]
> Im not seeing that line..
> https://github.com/steschuser/PowerDNS-Admin/blob/d2d7a4cc21945f7153f623b2250262d731e73fd0/powerdnsadmin/routes/admin.py#L124
> 
> There should be no current_app.logger.info(userperms) on line 124
> Can you remove that statement and give me traceback?

Hey, tested it now.
I still get the error: `UnboundLocalError: local variable 'userperms' referenced before assignment`
There is no logger but if the python code fails it will still cause the error even if no logger.

Full error:
```
Traceback (most recent call last):
  File "/var/www/html/PowerDNS-Admin/flask/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/var/www/html/PowerDNS-Admin/flask/lib/python3.6/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
    return self.app(environ, start_response)
  File "/var/www/html/PowerDNS-Admin/flask/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/var/www/html/PowerDNS-Admin/flask/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/html/PowerDNS-Admin/flask/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/var/www/html/PowerDNS-Admin/flask/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/html/PowerDNS-Admin/flask/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/html/PowerDNS-Admin/flask/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/html/PowerDNS-Admin/flask/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/var/www/html/PowerDNS-Admin/flask/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/html/PowerDNS-Admin/flask/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/html/PowerDNS-Admin/flask/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/var/www/html/PowerDNS-Admin/powerdnsadmin/decorators.py", line 32, in decorated_function
    return f(*args, **kwargs)
  File "/var/www/html/PowerDNS-Admin/powerdnsadmin/routes/admin.py", line 138, in edit_user
    userperms=userperms)
UnboundLocalError: local variable 'userperms' referenced before assignment
```

**Comment by jbe-dw** [comment]
Hello,

Thank you for the PR, #1171 is doing what you want. I'm closing this

**Pull request closed without merging**
