### PR TITLE
Improve performance of domain update

### PR DESCRIPTION
**Pull request by AdvanticGmbH**
* Previously the loop would always query the db even for none existing accounts
* Now cache previously looked up accounts and skip db queries for empty accounts

Loop time previously: 3.000699043273926 sec
Loop time now: 0.2798025608062744 sec

### CODE REVIEW

**Comment by AdvanticGmbH** [comment]
This drastically increases the loading time of the dashboard for us with around 1000 dns zones.
Maybe you could take a look at it @jbe-dw

**Comment by jbe-dw** [comment]
Nice one. You meant "decreases" I guess :p

I'm sorry we are not as fast as we intended for merging, but we should move on this month.

**Comment by AdvanticGmbH** [comment]
Yes, that is what I meant. ^^

**Comment by RGanor** [comment]
@AdvanticGmbH The numbers are very impressive! I look at this soon.
Thank you for the contribution!

**Pull request merged**
