### PR TITLE
Add yml to deploy on kubernetes

### PR DESCRIPTION
**Pull request by asilenkov**
YMLs to deploy powerdnsadmin in kubernetes cluster.

### CODE REVIEW

**Comment by ngoduykhanh** [comment]
Thanks for submitting the PR. Are you able to provide some notes/instructions on how to use it ?

**Comment by sn00p** [comment]
Yeah, sure, let me just get working version first. It depends on migrations issues discussed above. I'm going to test it first next few days.

**Comment by bitsofinfo** [comment]
Please get this out or a helm chart! much needed

**Comment by wagnst** [comment]
@bitsofinfo added issue https://github.com/ngoduykhanh/PowerDNS-Admin/issues/905 for this

**Comment by RGanor** [comment]
@asilenkov Thanks for your contribution!

**Pull request merged**
