### PR TITLE
WIP Update admin-lte

### PR DESCRIPTION
**Pull request by RGanor**
This is a work in progress to update the admin-lte package. help is needed with the updating the html correctly.
upgrade guide:
https://adminlte.io/docs/3.2/upgrade-guide.html

current status after just updating dependencies:
image

### CODE REVIEW

**Comment by Metrax** [comment]
As written in #782, i will help you with the adaption to AdminLTE 3.2.0.
Here is my current status:
image
I redesigned the sidebar navigation and the top navigation.
There is only an little issue with the brand in the top-left corner ... but i think i can fix it soon.
Nothing commited yet, just to let you know, that i'm working on it.

**Comment by RGanor** [comment]
wow that's an amazing progress! thank you for your help

**Comment by Metrax** [comment]
"Redesign" of login: done
image

**Comment by AzorianMatt** [comment]
This PR is actively being superseded by PR [1371](https://github.com/PowerDNS-Admin/PowerDNS-Admin/pull/1371) so I'm closing this one.

**Pull request closed without merging**
