### PR TITLE
Provide Catalog Zone Support

### PR DESCRIPTION
**Pull request by feldsam**
REFS #1607

### CODE REVIEW

**Comment by AzorianMatt** [comment]
@feldsam this morning I addressed a bug in PDA based on the use of zone names with forward slashes in the name. Would you mind applying this quick fix to your changes to the domain.py model file please? Reference PR 1707 for a direct example of the other changes I made which are very quick and simple.

**Comment by feldsam** [comment]
Hello @AzorianMatt , why I should apply your PR to my? When your will be merged before mine, them I solve possible conflicts.

**Comment by AzorianMatt** [comment]
@feldsam I was asking you to apply the simple URL encoding change so that I don't have to open a separate PR or do a separate set of commits to correct yours once merged. Does that make more sense?

Also, how should I test this? I have your copy checked out, but none of my record sets are loading when opening a zone to edit. Not really sure what is wrong there.

**Comment by feldsam** [comment]
No, it doesn't make sense. Why you do not merge your PR before mine? Them I pull changes and apply to my branch, slve conflicts.

**Comment by AzorianMatt** [comment]
@feldsam I don't think you understand, I already merged the changes into `dev`. You can merge them now if you like, but what I am asking is for you to replicate the type of change I made into your new code that is part of this PR. The code you added, will essentially re-create the bug I just fixed because it also doesn't account for the issue I was correcting. Just review the PR and you should see what I mean.

**Pull request merged**
