### PR TITLE
Finish Updating Zone Nomenclature From Domain

### PR DESCRIPTION
**Pull request by subbink**
This PR should (mostly) fix issue #1412 by changing the text domain to zone.
I have tested the basic functionality. It would be nice if someone else can also check nothing got broken.

### CODE REVIEW

**Review by AzorianMatt — COMMENTED** [review]
@subbink these changes generally speaking look great!

However, I do you see one problem that would be introduced by this change which we will need to tweak the PR for before merging. Due to how the history / activity feature has been written through the use of SQL like queries in some places, the logic will need updated to include not only the new nomenclature (`zone`), but also the previous nomenclature (`domain`). Otherwise, existing history / activity data will not be properly matched by the current logic after this change.

Let me know if you are comfortable working on this particular problem or if I should make the changes.

Thanks!

**Comment by subbink** [comment]
@AzorianMatt, I will have a go to fix those items.

**Comment by subbink** [comment]
I have made some changes to keep the old history items fully functional.

**Comment by AzorianMatt** [comment]
@subbink I'll try to carve out sometime tomorrow to circle back and do reviews and merges. Thank you for addressing that!

**Pull request merged**
