### PR TITLE
Added custom header to be used in the created_by column.

### PR DESCRIPTION
**Pull request by benshalev849**
I have added the feature as discussed here: 
https://github.com/PowerDNS-Admin/PowerDNS-Admin/discussions/1438

In addition some docs about the feature, it's use, and some other features.

### CODE REVIEW

**Comment by AzorianMatt** [comment]
@benshalev849 it looks like you may have been behind on a commit or two that I did this morning so there are merge conflicts present that need resolved.

Thanks!

**Comment by benshalev849** [comment]
@AzorianMatt Fixed

**Comment by AzorianMatt** [comment]
@benshalev849 thanks. My only other review item is the `basic_settings.md` file needs to be relocated to the `docs/wiki/configuration` directory to maintain the current file organization. After that, it appears your change is good for merging!

**Comment by benshalev849** [comment]
@AzorianMatt 

y, didn't know where to put it haha, change path :D

**Comment by AzorianMatt** [comment]
@benshalev849 My apologies for not clarifying that the first time, I'm bouncing around many different areas right now and haven't given it the full attention I should have! I'll get this merged after the automated checks clear.

**Pull request merged**
